# Generated by Django 2.2.4 on 2019-08-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('NIC', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=20)),
                ('serviceType', models.CharField(max_length=50)),
                ('profileImage', models.ImageField(upload_to='')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicleImage1', models.ImageField(upload_to='')),
                ('vehicleImage2', models.ImageField(upload_to='')),
                ('vehicleImage3', models.ImageField(upload_to='')),
                ('regNo', models.CharField(max_length=100)),
                ('numberOfPassenger', models.IntegerField()),
                ('acCondition', models.BinaryField()),
                ('insExpDate', models.DateField()),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=20)),
                ('NIC', models.CharField(max_length=100)),
                ('licenseNO', models.CharField(max_length=100)),
                ('profileImage', models.ImageField(upload_to='')),
                ('drivingLicenseImage', models.ImageField(upload_to='')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('companyOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
            ],
        ),
    ]
