# Generated by Django 2.2.4 on 2019-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profileImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='ImageFolder/'),
        ),
    ]
