# Generated by Django 2.2.4 on 2019-08-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(max_length=200)),
                ('travelLocation', models.CharField(max_length=200)),
                ('numberOfPassenger', models.IntegerField()),
                ('arrivalDate', models.DateField()),
                ('departureDate', models.DateField()),
                ('pickLocation', models.CharField(max_length=200)),
                ('acCondition', models.BooleanField(default=False)),
                ('wayPoints', models.CharField(max_length=5000)),
                ('tourDescription', models.TextField(max_length=5000)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
